"""
SecureMailScope — HTML Security Report Generator.

Produces a standalone, dark-themed HTML report with inline CSS
containing all 10 required sections.  The report is designed to
be print-friendly and downloadable.
"""

from datetime import datetime, timezone
from app.models.schemas import AnalysisResult, AnalysisStatus, Severity


class ReportGenerator:
    """Generate professional HTML security reports."""

    @staticmethod
    def generate(result: AnalysisResult) -> str:
        css = ReportGenerator._css()
        body = ReportGenerator._body(result)
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SecureMailScope Report — {result.id}</title>
    {css}
</head>
<body>
    <div class="container">
        <header>
            <div class="logo">🛡️ SecureMailScope</div>
            <div class="subtitle">AI-Assisted Cryptographic Security Posture Assessment</div>
            <div class="report-meta">
                Report ID: {result.id}<br>
                Generated: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
            </div>
        </header>
        {body}
        <footer>
            <p>Generated by SecureMailScope v1.0.0 &mdash; AI-Assisted Cryptographic Security Posture Assessment</p>
            <p>This report is intended for internal security review purposes.</p>
        </footer>
    </div>
</body>
</html>"""

    @staticmethod
    def _body(result: AnalysisResult) -> str:
        # Handle NOT_APPLICABLE
        if result.status == AnalysisStatus.NOT_APPLICABLE:
            detected = ", ".join(result.detected_traffic_types or ["Unknown"])
            return f"""
            <div class="section">
                <h2>Analysis Result: Not Applicable</h2>
                <div class="alert alert-info">
                    <strong>No supported email communication was detected in this PCAP.</strong>
                </div>
                <table>
                    <tr><td>Detected Traffic Types</td><td>{detected}</td></tr>
                    <tr><td>Email Sessions Found</td><td>0</td></tr>
                    <tr><td>Supported Protocols</td><td>SMTP, IMAP, POP3</td></tr>
                </table>
                <p><strong>Recommendation:</strong> Upload a PCAP containing SMTP (25/465/587), IMAP (143/993), or POP3 (110/995) traffic.</p>
            </div>"""

        ra = result.risk_assessment
        score = ra.score if ra else 0
        level = ra.level.value if ra else "N/A"
        confidence = f"{ra.confidence:.0%}" if ra else "N/A"

        severity_map = {
            "CRITICAL": "#ef4444", "HIGH": "#f59e0b",
            "MEDIUM": "#3b82f6", "LOW": "#10b981", "INFO": "#6b7280"
        }
        level_color = {
            "LOW": "#10b981", "MEDIUM": "#f59e0b",
            "HIGH": "#f97316", "CRITICAL": "#ef4444"
        }

        # ── 1. Executive Summary ──
        total = result.total_sessions
        enc = result.encrypted_sessions
        unenc = result.unencrypted_sessions
        crit_count = sum(1 for f in result.findings if f.severity == Severity.CRITICAL)
        high_count = sum(1 for f in result.findings if f.severity == Severity.HIGH)
        med_count = sum(1 for f in result.findings if f.severity == Severity.MEDIUM)

        s1 = f"""
        <div class="section">
            <h2>1. Executive Summary</h2>
            <p>This report presents the results of an automated cryptographic security posture assessment
            of email network traffic captured in PCAP format.  The analysis evaluated <strong>{total}</strong>
            email session(s) across {', '.join(result.protocol_counts.keys())} protocol(s).</p>
            <p>The assessment identified <span class="badge badge-critical">{crit_count} Critical</span>,
            <span class="badge badge-high">{high_count} High</span>, and
            <span class="badge badge-medium">{med_count} Medium</span> severity findings.</p>
        </div>"""

        # ── 2. Overall Score ──
        s2 = f"""
        <div class="section">
            <h2>2. Overall Security Score</h2>
            <div class="score-display" style="border-color: {level_color.get(level, '#666')}">
                <div class="score-number" style="color: {level_color.get(level, '#fff')}">{score}</div>
                <div class="score-label">/ 100</div>
                <div class="risk-level" style="background: {level_color.get(level, '#666')}">{level}</div>
            </div>
            <p>Confidence: {confidence}</p>
        </div>"""

        # ── 3. Traffic Summary ──
        proto_rows = "".join(
            f"<tr><td>{k}</td><td>{v}</td></tr>"
            for k, v in result.protocol_counts.items()
        )
        tls_rows = ""
        if result.tls_version_counts:
            tc = result.tls_version_counts
            for label, count in [
                ("TLS 1.3", tc.tls_1_3), ("TLS 1.2", tc.tls_1_2),
                ("TLS 1.1", tc.tls_1_1), ("TLS 1.0", tc.tls_1_0),
                ("SSL", tc.ssl), ("Unencrypted", tc.unencrypted),
            ]:
                if count > 0:
                    tls_rows += f"<tr><td>{label}</td><td>{count}</td></tr>"

        s3 = f"""
        <div class="section">
            <h2>3. Traffic Summary</h2>
            <div class="grid-2">
                <div>
                    <h3>Protocol Distribution</h3>
                    <table><tr><th>Protocol</th><th>Sessions</th></tr>{proto_rows}</table>
                </div>
                <div>
                    <h3>Encryption Overview</h3>
                    <table>
                        <tr><td>Total Sessions</td><td>{total}</td></tr>
                        <tr><td>Encrypted</td><td>{enc}</td></tr>
                        <tr><td>Unencrypted</td><td>{unenc}</td></tr>
                    </table>
                    {f'<h3>TLS Versions</h3><table><tr><th>Version</th><th>Count</th></tr>{tls_rows}</table>' if tls_rows else ''}
                </div>
            </div>
        </div>"""

        # ── 4. Email Sessions ──
        session_rows = ""
        for s in result.sessions:
            cd = s.crypto_details
            tls_v = cd.tls_version if cd else "None"
            cipher = cd.cipher_suite if cd else "None"
            r_score = s.risk_score or 0
            r_level = s.risk_level or "N/A"
            session_rows += f"""
            <tr>
                <td>{s.id}</td>
                <td>{s.protocol}</td>
                <td>{s.src_ip} → {s.dst_ip}:{s.dst_port}</td>
                <td>{tls_v}</td>
                <td>{cipher}</td>
                <td><span class="badge badge-{r_level.lower()}">{r_score} ({r_level})</span></td>
            </tr>"""

        s4 = f"""
        <div class="section">
            <h2>4. Email Sessions</h2>
            <table>
                <tr><th>ID</th><th>Protocol</th><th>Connection</th><th>TLS</th><th>Cipher</th><th>Risk</th></tr>
                {session_rows}
            </table>
        </div>"""

        # ── 5. TLS Analysis ──
        tls_details = ""
        for s in result.sessions:
            cd = s.crypto_details
            if cd and cd.tls_version not in ("None", "", None):
                tls_details += f"""
                <div class="detail-card">
                    <h4>{s.hostname or s.dst_ip}:{s.dst_port}</h4>
                    <table>
                        <tr><td>TLS Version</td><td>{cd.tls_version}</td></tr>
                        <tr><td>Cipher Suite</td><td>{cd.cipher_suite}</td></tr>
                        <tr><td>STARTTLS</td><td>{'Yes' if cd.starttls_used else 'No'}</td></tr>
                        <tr><td>Handshake</td><td>{cd.handshake_status}</td></tr>
                    </table>
                </div>"""

        s5 = f"""
        <div class="section">
            <h2>5. TLS Analysis</h2>
            {tls_details if tls_details else '<p>No TLS sessions detected.</p>'}
        </div>"""

        # ── 6. Certificate Analysis ──
        cert_details = ""
        for s in result.sessions:
            cd = s.crypto_details
            if cd and cd.tls_version not in ("None", "", None):
                cert_details += f"""
                <div class="detail-card">
                    <h4>{s.hostname or s.dst_ip}</h4>
                    <table>
                        <tr><td>Valid</td><td>{'✅ Yes' if cd.cert_valid else '❌ No'}</td></tr>
                        <tr><td>Expired</td><td>{'❌ Yes' if cd.cert_expired else '✅ No'}</td></tr>
                        <tr><td>Self-Signed</td><td>{'⚠️ Yes' if cd.self_signed else '✅ No'}</td></tr>
                        <tr><td>Hostname Match</td><td>{'✅ Yes' if cd.hostname_match else '❌ No'}</td></tr>
                        <tr><td>Chain Valid</td><td>{'✅ Yes' if cd.chain_valid else '❌ No'}</td></tr>
                        <tr><td>Key Size</td><td>{cd.key_size} bits</td></tr>
                        <tr><td>Signature Algorithm</td><td>{cd.signature_algorithm}</td></tr>
                        <tr><td>Issuer</td><td>{cd.cert_issuer or 'N/A'}</td></tr>
                        <tr><td>Expiry</td><td>{cd.cert_expiry_date or 'N/A'}</td></tr>
                    </table>
                </div>"""

        s6 = f"""
        <div class="section">
            <h2>6. Certificate Analysis</h2>
            {cert_details if cert_details else '<p>No certificates to analyse.</p>'}
        </div>"""

        # ── 7. Cryptographic Weaknesses ──
        crypto_findings = [f for f in result.findings if "cipher" in f.title.lower() or "key" in f.title.lower() or "signature" in f.title.lower()]
        crypto_html = ""
        for f in crypto_findings:
            crypto_html += f"""
            <div class="finding finding-{f.severity.value.lower()}">
                <div class="finding-header"><span class="badge badge-{f.severity.value.lower()}">{f.severity.value}</span> {f.title}</div>
                <p>{f.description}</p>
                <p class="evidence"><strong>Evidence:</strong> {f.evidence}</p>
            </div>"""

        s7 = f"""
        <div class="section">
            <h2>7. Cryptographic Weaknesses</h2>
            {crypto_html if crypto_html else '<p>No cryptographic weaknesses detected.</p>'}
        </div>"""

        # ── 8. Vulnerability Findings ──
        findings_html = ""
        for f in sorted(result.findings, key=lambda x: ["CRITICAL","HIGH","MEDIUM","LOW","INFO"].index(x.severity.value)):
            findings_html += f"""
            <div class="finding finding-{f.severity.value.lower()}">
                <div class="finding-header">
                    <span class="badge badge-{f.severity.value.lower()}">{f.severity.value}</span>
                    {f.title}
                </div>
                <p>{f.description}</p>
                <p class="evidence"><strong>Evidence:</strong> {f.evidence}</p>
                <p><strong>Impact:</strong> {f.impact}</p>
                <p><strong>Remediation:</strong> {f.recommendation}</p>
            </div>"""

        s8 = f"""
        <div class="section">
            <h2>8. Vulnerability Findings</h2>
            {findings_html if findings_html else '<p>No vulnerabilities found.</p>'}
        </div>"""

        # ── 9. AI Risk Assessment ──
        factors_html = ""
        if ra and ra.feature_contributions:
            factors_html = '<div class="contributions">'
            for c in ra.feature_contributions[:8]:
                bar_w = min(c.contribution * 2, 100)
                factors_html += f"""
                <div class="contrib-row">
                    <span class="contrib-label">{c.description}</span>
                    <div class="contrib-bar-bg">
                        <div class="contrib-bar" style="width:{bar_w}%"></div>
                    </div>
                    <span class="contrib-val">+{c.contribution:.0f}</span>
                </div>"""
            factors_html += "</div>"

        s9 = f"""
        <div class="section">
            <h2>9. AI Risk Assessment</h2>
            <p>The ML-based risk engine (RandomForest classifier) analysed {total} sessions
            and produced the following assessment:</p>
            <table>
                <tr><td>Risk Score</td><td>{score} / 100</td></tr>
                <tr><td>Risk Level</td><td>{level}</td></tr>
                <tr><td>Model Confidence</td><td>{confidence}</td></tr>
            </table>
            <h3>Contributing Factors</h3>
            {factors_html if factors_html else '<p>No significant risk factors identified.</p>'}
        </div>"""

        # ── 10. Remediation ──
        recs_html = ""
        if result.recommendations:
            recs_html = "<ol>" + "".join(f"<li>{r}</li>" for r in result.recommendations) + "</ol>"
        else:
            recs_html = "<p>No specific remediation steps required.</p>"

        s10 = f"""
        <div class="section">
            <h2>10. Recommended Remediation</h2>
            {recs_html}
        </div>"""

        return s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + s10

    @staticmethod
    def _css() -> str:
        return """<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
        font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
        background: #0a0e1a; color: #e0e6f0; line-height: 1.6;
    }
    .container { max-width: 960px; margin: 0 auto; padding: 40px 30px; }
    header { text-align: center; margin-bottom: 40px; padding-bottom: 30px; border-bottom: 1px solid #1e293b; }
    .logo { font-size: 28px; font-weight: 700; color: #06b6d4; margin-bottom: 5px; }
    .subtitle { color: #94a3b8; font-size: 14px; }
    .report-meta { margin-top: 15px; font-size: 12px; color: #64748b; }
    h2 { color: #f1f5f9; font-size: 20px; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #1e293b; }
    h3 { color: #cbd5e1; font-size: 16px; margin: 16px 0 10px; }
    h4 { color: #e2e8f0; font-size: 14px; margin-bottom: 8px; }
    .section { background: #111827; border: 1px solid #1e293b; border-radius: 8px; padding: 24px; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 13px; }
    th { background: #1e293b; color: #94a3b8; text-align: left; padding: 10px 12px; font-weight: 600; }
    td { padding: 10px 12px; border-bottom: 1px solid #1e293b; }
    .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
    .score-display { text-align: center; padding: 30px; border: 2px solid; border-radius: 12px; display: inline-block; min-width: 200px; }
    .score-number { font-size: 56px; font-weight: 800; }
    .score-label { font-size: 18px; color: #94a3b8; }
    .risk-level { display: inline-block; padding: 4px 16px; border-radius: 20px; color: #fff; font-weight: 700; font-size: 14px; margin-top: 10px; }
    .badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 11px; font-weight: 600; color: #fff; }
    .badge-critical { background: #ef4444; }
    .badge-high { background: #f59e0b; }
    .badge-medium { background: #3b82f6; }
    .badge-low { background: #10b981; }
    .badge-info { background: #6b7280; }
    .detail-card { background: #1e293b; border-radius: 6px; padding: 16px; margin-bottom: 12px; }
    .finding { border-left: 4px solid #64748b; padding: 16px; margin: 12px 0; background: #1e293b; border-radius: 0 6px 6px 0; }
    .finding-critical { border-left-color: #ef4444; }
    .finding-high { border-left-color: #f59e0b; }
    .finding-medium { border-left-color: #3b82f6; }
    .finding-low { border-left-color: #10b981; }
    .finding-header { font-weight: 600; margin-bottom: 8px; font-size: 14px; }
    .finding p { font-size: 13px; margin: 6px 0; color: #cbd5e1; }
    .evidence { color: #94a3b8 !important; font-style: italic; }
    .contributions { margin-top: 12px; }
    .contrib-row { display: flex; align-items: center; margin: 8px 0; font-size: 13px; }
    .contrib-label { flex: 0 0 280px; color: #cbd5e1; }
    .contrib-bar-bg { flex: 1; height: 8px; background: #1e293b; border-radius: 4px; margin: 0 12px; }
    .contrib-bar { height: 100%; background: linear-gradient(90deg, #06b6d4, #f59e0b); border-radius: 4px; }
    .contrib-val { flex: 0 0 50px; text-align: right; color: #f59e0b; font-weight: 600; }
    .alert { padding: 16px; border-radius: 6px; margin: 12px 0; }
    .alert-info { background: #1e3a5f; border: 1px solid #2563eb; }
    footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #1e293b; color: #64748b; font-size: 12px; }
    footer p { margin: 4px 0; }
    @media print {
        body { background: #fff; color: #1e293b; }
        .section { border-color: #e2e8f0; background: #fff; }
        th { background: #f1f5f9; color: #334155; }
        td { border-color: #e2e8f0; }
        .detail-card { background: #f8fafc; }
        .finding { background: #f8fafc; }
    }
</style>"""
